"""empty message

Revision ID: 2a763d21b147
Revises: 42c7a522aa6b
Create Date: 2021-01-14 14:09:12.011564

"""

# revision identifiers, used by Alembic.
revision = '2a763d21b147'
down_revision = '42c7a522aa6b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_hours',
    sa.Column('studentid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learninghours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpuusage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courseid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('noofmoudles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxnoofsubmission', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batchid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('studentid', name='learning_hours_pkey')
    )
    # ### end Alembic commands ###
