"""empty message

Revision ID: 42c7a522aa6b
Revises: 51e2c29ad95
Create Date: 2021-01-13 12:26:24.127820

"""

# revision identifiers, used by Alembic.
revision = '42c7a522aa6b'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dept')
    # ### end Alembic commands ###
